.github/workflows/verify-dependabot.yml
- Dependabot checks for this repository need access to secrets in order to be tested. Recent changes at Github prevents "normal" PRs from Dependabot to be tested (since they now get a read-only Github token and no secrets).
- This PR changes that allowing Dependabot PRs to run in a "trusted" environment again via `pull_request_target`.
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests
See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
See https://github.com/dependabot/dependabot-core/issues/3253
The following steps are required for testing and verifying.
- Wait for a `dependabot[bot]` PR and hope it succeeds
- Create a "user" PR (like this one) and see that that the Checks …
=> fix(ci): dependabot PRs fixes

packages/eslint-config-prettier/react.js
Dependabot upgraded eslint-config-prettier in https://github.com/reside-eng/lint-config/pull/107 which included a breaking change: 
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
This caused an error message when using this config in a new repo:
```(node:8408) UnhandledPromiseRejectionWarning: Error: Cannot read config file: /Users/jonathanmay/side/documents-ui/node_modules/eslint-config-prettier/react.js
Error: "prettier/react" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /Users/jonathanmay/side/documents-ui/node_modules/@side/eslint-config-prettier/react.js```
=> fix: update extends for eslint-config-prettier v8 changes

packages/eslint-config-jest/eslint-config-jest.js
Jest publishes a recommended ESLint ruleset as part of its `eslint-config-jest` package. However, it looks like this repo has been using `jest/all` as one of its extended rulesets. 
`jest/all` enables every single lint rule provided by `eslint-config-jest`. 
From the [docs](https://github.com/jest-community/eslint-plugin-jest#all) for `eslint-config-jest` regarding `jest/all` (emphasis added):
> While the `recommended` and `style` configurations only change in major versions, _the `all` configuration may change in any release_ and is thus unsuited for installations requiring long-term consistency.
This PR replaces `jest/all` with `jest/recommended`, with the primary reason for the change being that Jest only recommends enabling a subset of its rules by default. 
If `jest/all` was …
=> fix: replace `jest/all` with `jest/recommended`

packages/eslint-config-base/rules/imports.js, packages/eslint-config-react/eslint-config-react.js, packages/eslint-config-react/rules/import.js
This PR updates our lint config to adhere to the merged proposal on import/export patterns: reside-eng/guidelines#2
- Turned off `import/prefer-default-export`.
- Turned on `import/no-default-export`.
- Added overrides to allow default exports for the following scenarios:
- Storybook stories
- Next.js pages and API routes
- Next.js config
- Jest config
=> feat: update rules for default exports [PLAT-1239]

packages/eslint-config-react/rules/import.js
Added missing overrides for Next.js API routes. These were missed the first time because the files in `**/api/**` do not use JSX, so the extensions did not match up.
=> fix: add missing default export overrides

packages/eslint-config-react/eslint-config-react.js, packages/eslint-config-react/rules/base.js
- Added a new error lint rule to the react lint config that disallows importing `React.FC`
=> feat: disallow `React.FC` for react projects

packages/eslint-config-react/package.json, yarn.lock
https://github.com/airbnb/javascript/blob/eslint-config-airbnb-v19.0.4/packages/eslint-config-airbnb/CHANGELOG.md#1903--2021-12-24
We're a couple revisions behind and currently there's an error with the syntax on the 1react/function-component-definition` from airbnb:
```
> yarn lint
yarn run v1.22.17
$ next lint --dir .
info  - Loaded env from /Users/jesse/Code/template-nextjs/.env.local
info  - Loaded env from /Users/jesse/Code/template-nextjs/.env
Error: .eslintrc.js » @side/eslint-config-react » /Users/jesse/Code/template-nextjs/node_modules/eslint-config-airbnb/index.js » /Users/jesse/Code/template-nextjs/node_modules/eslint-config-airbnb/rules/react.js:
Configuration for rule "react/function-component-definition" is invalid:
Value ["function-declaration","function-expression"] should …
```
=> chore(dev-deps): update eslint-config-airbnb@19.0.4

packages/eslint-config-react/package.json, yarn.lock
Even after the update to the latest `eslint-config-airbnb`, I'm still experiencing the problem in around the function component definition rule. After looking deeper, I discovered the peer dependency version of the `eslint-plugin-react` library is also outdated. This PR makes this additional update.
=> fix: update eslint-config-react to meet eslitnt-config-airbnb's peer dependency demands

.github/workflows/release.yml, .github/workflows/verify-dependabot.yml, .github/workflows/verify.yml, package.json
Also drops the unnecessary usage of matrix - this will mean we have to update status check settings, but that can be done after merge.
=> chore(build): upgrade node from 14 to 16 [PLAT-1082]

packages/eslint-config-base/rules/errors.js
Updates our eslint rules for this RFC:  https://github.com/reside-eng/guidelines/blob/main/rfcs/shared-patterns/typescript/002-class-methods-use-this.md
set the rule `class-methods-use-this` to off
=> fix: turn off class-methods-use-this rule

packages/eslint-config-react/rules/base.js
This PR turns off the ESLint rule [`no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define) for function declarations. Classes and variables will remain subject to this rule.
=> feat: allow reordering of function declarations

packages/eslint-config-base/rules/errors.js
Disabled the [`arrow-body-style`](https://eslint.org/docs/rules/arrow-body-style) lint rule in accordance with the UI Working Group decision from the March 25, 2022 meeting.
=> fix: disable `arrow-body-style` lint rule

packages/eslint-config-typescript/README.md, packages/eslint-config-typescript/eslint-config-typescript.js, packages/eslint-config-typescript/package.json, packages/eslint-config-typescript/rules/import.js, packages/eslint-config-typescript/rules/react.js, packages/eslint-config-typescript/without-type-checks.js, yarn.lock
- Added `@typescript-eslint/parser` as a dependency.
- Switched TypeScript file glob to match Next.js's pattern.
- Added documentation for troubleshooting multiple `tsconfig.json` files.
=> fix: correct TypeScript parsing issues

packages/eslint-config-base/rules/imports.js
firebase-admin has imports defined in package.json which eslint-plugin-import does not currently support [as described in this issue](https://github.com/import-js/eslint-plugin-import/issues/1810)
=> feat(base): add support for firebase-admin v10 imports [PLAT-1324]

packages/lint-staged-config/README.md, packages/lint-staged-config/index.js, packages/lint-staged-config/package.json
Add lint staged config so it can be shared across projects.  This is a configuration that I've seen added to several repos so we correctly ignore linting files that should be ignored by the .eslintignore file
=> feat: add shared lint staged config

packages/eslint-config-base/rules/imports.js
Adds `lint-staged.config.js` to imports settings to prevent extraneous dependencies lint error
=> fix: add lint-staged.config file to imports settings

packages/eslint-config-jest/index.js, packages/eslint-config-jest/package.json, yarn.lock
Add jest formatting rules to keep our test files consistent.  All rules are fixable 
https://github.com/dangreenisrael/eslint-plugin-jest-formatting#readme
=> feat(config-jest): add jest formatting rules

packages/eslint-config-base/rules/errors.js
Turned off the `no-restricted-syntax` rule.
By turning off this rule, we are allowed to use `for..of` to iterate over any iterable object, be it an Array, Map, Set, etc.
It appears that the rule existed for compatibility purposes for supporting pre-ES2015 environments that would have required babel runtime to support iterators.
=> feat: allow loops over iterators

packages/eslint-config-jest/index.js, packages/eslint-config-jest/package.json, yarn.lock
📜 reside-eng/guidelines#19
Adds a lint warning when a test file uses `.test` instead of `.spec`.
=> feat: warn when `.test` is used instead of `.spec`

packages/eslint-config-react/rules/react.js
That was the intention of #409 but since it's enabled by default in airbnb's config, my change just removed our override. My bad.
=> feat: truly disable react/require-default-props

packages/jest-config-next/.gitignore, packages/jest-config-next/dist/index.d.ts, packages/jest-config-next/dist/index.js, packages/jest-config-next/dist/internals/base.d.ts, packages/jest-config-next/dist/internals/base.js, packages/jest-config-next/dist/internals/logs.d.ts, packages/jest-config-next/dist/internals/logs.js, packages/jest-config-next/dist/internals/verification.d.ts, packages/jest-config-next/dist/internals/verification.js, packages/jest-config-next/dist/make.d.ts, packages/jest-config-next/dist/make.js, packages/jest-config-next/package.json
Due to lerna build issues, this PR includes the `dist` directory of the Next.js Jest package within version control.
Building packages at runtime using our current yarn workspaces/lerna configuration is causing build failures with Typescript packages. It appears that there is unwanted hoisting going on that causes the wrong version of TypeScript to be used when building the `@side/jest-config-next` package. 
Including the `dist` for that package in version control seems to be an effective remedy for this issue until we can debug the larger issue with lerna/yarn.
=> ci: include Next.js Jest package dist in git

packages/commitlint-config/CHANGELOG.md, packages/commitlint-config/package.json, packages/eslint-config-base/CHANGELOG.md, packages/eslint-config-base/package.json, packages/eslint-config-cypress/CHANGELOG.md, packages/eslint-config-cypress/package.json, packages/eslint-config-jest/CHANGELOG.md, packages/eslint-config-jest/package.json, packages/eslint-config-next/CHANGELOG.md, packages/eslint-config-next/package.json, packages/eslint-config-react/CHANGELOG.md, packages/eslint-config-react/package.json, packages/jest-config-next/CHANGELOG.md, packages/jest-config-next/package.json, packages/lint-staged-config/CHANGELOG.md, packages/lint-staged-config/package.json, packages/prettier-config/CHANGELOG.md, packages/prettier-config/package.json
Bump packages to stable versions.
Packages that depended on `v0.x` have also received a major version bump, since that's how Lerna appears to handle it.
=> chore(release): bump versions

packages/prettier-config/index.json
Fixes prettier error seen from GH credentials through shared config so that each repo doesn't need to ignore this file
Issue seen here: https://github.com/reside-eng/test-nextjs-ci/actions/runs/4821766907/jobs/8588109192#step:23:43
=> fix: ignore gha-creds-*.json in prettier config

packages/eslint-config-typescript/rules/typescript-eslint.js
Turned off a rule that tried to enforce a convention of using only `type` or `interface`, but not both.
We use both keywords across our projects for different reasons. The recent major update to TypeScript ESLint added a rule that requires you to prefer one or the other. This PR turns that rule off, since we don't have an official recommendation to prefer one variant.
=> feat(eslint-typescript): turn off types/interfaces rule

packages/lint-staged-config/index.js
* Switch to ignore-path argument within call to prettier instead of custom files array - this makes the debug logs from lint-staged debug more clear and avoids some cases of erroneous error messages from lint-staged
=> fix(lint-staged-config): use ignore-path instead of custom files list

packages/eslint-config-base/rules/imports.js, packages/eslint-config-typescript/rules/import.js, packages/eslint-config-typescript/rules/typescript-eslint.js
* Support default exports within config files (now used in repos which are native ESM):
* `commitlint.config.js`
* `lint-staged.config.js`
* `release.config.js`
* Add import extension support for `.cjs`
* Add nested import support for `vitest.config.js` (importing `vitest/config` triggers import/no-unresolved due to package imports)
=> fix: support default export in config files for ESM repos

packages/jest-config-next/src/internals/base.ts
:tickets: [PAY-7640](https://residenetwork.atlassian.net/browse/PAY-7640)
Added the GitHub Actions reporter to our Jest reporters configuration.
Review an example of this configuration here:
- https://github.com/reside-eng/payment-ui/pull/2566
- [Workflow Annotations](https://github.com/reside-eng/payment-ui/actions/runs/10476107025) 
- [Changed Files](https://github.com/reside-eng/payment-ui/pull/2566/files)
[PAY-7640]: https://residenetwork.atlassian.net/browse/PAY-7640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add GitHub Actions reporters [PAY-7640]

packages/eslint-config-base/rules/imports.js
* Add support for `mts` and `cts` file extensions on config files (specifically vitest)
* Remove unused configs from airbnb that we will never use (karma, protractor, gulp etc)
=> feat(base): support mts configs
