reside-eng/lint-config

.github/workflows/verify-dependabot.yml, .github/workflows/verify.yml, package.json
BREAKING CHANGE: Drop Node 10 and 12 support
=> chore: drop Node 10 and 12 support

packages/eslint-config-react/rules/react.js
Per the vote on https://github.com/reside-eng/guidelines/discussions/25
=> feat: remove react/require-default-props

.github/workflows/release.yml, .github/workflows/verify.yml, .prettierrc.js, package.json, packages/jest-config-next/package.json, packages/jest-config-next/src/internals/base.ts, packages/jest-config-next/src/internals/verification.ts
- Added lerna command to run build script (if present) in workspace packages during CI.
- Added `prepublish` script to Jest config package to build before publishing.
=> fix: add prepublish to build package

packages/jest-config-next/src/internals/verification.ts, packages/jest-config-next/tsconfig.json
- Fixed typo.
- Added declaration map to build output.
=> fix(jest-config-next): include declaration map and fix package.json import

.github/workflows/verify.yml
=> ci: support MQ

lerna.json
=> fix: remove useWorkspaces from lerna config

packages/eslint-config-next/index.js, packages/eslint-config-next/package.json, packages/eslint-config-next/rules/graphql.js, yarn.lock
:tickets: ASP-2236 
- Added `@graphql-eslint/eslint-plugin` to validate graphql operation files in `eslint-config-next`.
=> feat(eslint-config-next): add graphql operations recommended rules

package.json, yarn.lock
Reverts reside-eng/lint-config#563
=> Revert "chore(dev-deps): update dependency prettier to v3.0.3"

package.json, yarn.lock
- Upgrade lerna to latest major
=> fix: upgrade lerna

.github/workflows/release.yml
=> fix(ci): disable coverage on release

packages/eslint-config-next/rules/import.js
=> feat(next): add support for codegen.ts

packages/eslint-config-next/rules/graphql.js
=> fix(next): allow underscore dangle for typename

package.json, renovate.json, yarn.lock
Revert update to v8 of Lerna in this PR: https://github.com/reside-eng/lint-config/pull/585 due to issues in release: https://github.com/reside-eng/lint-config/actions/runs/7303447146/job/19903969987#step:18:14
=> fix(deps): downgrade lerna to v7

packages/eslint-config-base/rules/imports.js
=> fix(base): prevent false negative on restricted imports

packages/eslint-config-base/rules/imports.js
* fix(base): remove references to firebase-admin
=> fix: use paths for more accurate restricted imports

packages/eslint-config-typescript/rules/typescript-eslint.js
**BREAKING CHANGE**
Add rule to require type import where only types are used - this prevents type only code from being included in code transpiled by tsc into commonjs (services). We have seen lower cold start times due to less code being loaded just by enforcing type imports:
**Incorrect**
```ts
import { Foo } from 'Foo';
import Bar from 'Bar';
type T = Foo;
const x: Bar = 1;
```
**Correct**
```ts
import type { Foo } from 'Foo';
import type Bar from 'Bar';
type T = Foo;
const x: Bar = 1;
```
See [the typescript-eslint docs for the rule for more info](https://typescript-eslint.io/rules/consistent-type-imports/)
This will be a breaking change
* Right now this is enforced for all Typescript, not just services (where we need it) - do we think this should only be on …
=> feat(typescript)!: force type imports

packages/eslint-config-typescript/rules/typescript-eslint.js
=> fix(typescript): add back consistent-type-definitions disable

packages/eslint-config-base/rules/imports.js
https://github.com/reside-eng/identity-functions/pull/310/files/4cc81f6b8442649e4ebbb7029f57b7f5b1669fee#r1492870404
* Add support for Vitest as well as cjs/mjs extensions on config files to support ESM as described [in this PR comment](https://github.com/reside-eng/identity-functions/pull/310/files/4cc81f6b8442649e4ebbb7029f57b7f5b1669fee#r1492870404)
=> feat: add cjs/mjs extensions for ESM support

packages/lint-staged-config/index.js
* Skip running prettier on files which are in `.eslintignore` - currently even files in .prettierignore may be picked up (how they were before with .eslintignore (which is why we put the logic in to skip those - I'm just updating prettier to work the same way). Its good for us to have this based on eslint's ignore (since they expose API for us to check that, which we are using) - also as called out below we are looking to have `.eslintignore` be the single source of truth for formatting ignore instead of multiple ignore files
This also allows us to update repos to use `.eslintignore` as ignore file for prettier (as part of removing `.prettierignore` from a repo, one should also set `--ignore-path=.eslintignore` within `format` and `format:verify` npm scripts - this …
=> fix(lint-staged-config): skip prettier on lint ignored files

packages/eslint-config-next/rules/import.js, packages/eslint-config-react/rules/import.js
- Allow default exports in app directory.
- Move Next.js rules from React to Next package.
=> fix: allow default exports in app directory

packages/eslint-config-base/rules/imports.js, packages/eslint-config-typescript/rules/import.js
=> fix: include mts and cts in import/extensions

.github/workflows/release.yml, .github/workflows/verify.yml
ref: https://github.com/reside-eng/workflow-templates-library/pull/66
=> fix: remove not needed inputs

.github/workflows/release.yml
=> chore(ci): skip dependency reporting

.github/workflows/release.yml, .github/workflows/verify.yml
Update to Node 22 - this isn't marked as a fix/feat because this is just the node version used in CI and we do not build these libraries (they are all written in common js)
=> chore(ci): update to node 22

.github/workflows/verify-pr-format.yml
=> ci: add pr title verify
